# Generated by Django 2.2 on 2020-12-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0003_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dishes')),
            ],
        ),
    ]
