# Generated by Django 2.2 on 2020-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.FileField(upload_to='images/')),
                ('designation', models.CharField(max_length=140)),
                ('abbr', models.CharField(max_length=140)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
