# Generated by Django 2.2 on 2020-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishId', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=140)),
                ('date', models.DateField()),
            ],
        ),
    ]
