# Generated by Django 2.2 on 2020-12-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
